### ISSUE TITLE
Plan for multiple time chunks

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/nawqa_wqp#2]
The starter files just pull one big time chunk, but we should plan for multiple time chunks, both for the inventory and for the actual data pull

**Comment by lindsaycarr** [comment]
I'm looking into this now. Wondering if you can explain a little bit more about this line https://github.com/USGS-R/nawqa_wqp/blob/master/1_wqpdata/src/wqp_inventory.R#L37 @aappling-usgs

**Comment by aappling-usgs** [comment]
We've thought about this some more  and think it's not worth it for a number of reasons. If you ever want to re-inventory the WQP, you should be prepared for remake to want to re-pull all times and probably also locations, because the inventory is likely to change in both those areas.
