### ISSUE TITLE
Split inventory by constituent

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/nawqa_wqp#3]
Rather than a single inventory file for all constituents, let's make it possible to update/add one or a few constituents at a time. This'll be more important as we move toward fuller and fuller data pulls.

**Comment by lindsaycarr** [comment]
@aappling-usgs I haven't gotten this to work yet because of how I've named targets, but I wanted your opinion to see if you think this is the right path https://github.com/lindsaycarr/nawqa_wqp/commit/2f778a7f883c1c1ffb01a654029e65dd27fe3fa4

**Comment by aappling-usgs** [comment]
@lindsaycarr I think for the separate inventories to save us builds, it'll be necessary to declare them as separate targets. This can be done either by manually creating a near-identical target for each constituent or by creating a task table - I think either of those approaches could work.

**Comment by lindsaycarr** [comment]
huh, ok. Do you have an example of a task table? I thought of the targets too, but thought it wouldn't be smart to manually add those since there will be more than 3 in the future.

**Comment by aappling-usgs** [comment]
Sure, here's an example of creating a task plan, creating a task .yml file, and then looping through the tasks in that .yml file: https://github.com/USGS-R/nawqa_wqp/blob/master/1_wqpdata.yml#L92-L108

**Comment by lindsaycarr** [comment]
Done thanks to #14
